version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-157-16-196.compute-1.amazonaws.com
            port: '5432'
            database: d8je60r13g4imj
            schema: schema.graphql
            user: bnopbhntvljhfs
            password: a33e8bad9b3116d0d9e8a13b092edb9c53eae35ad70f26389a1799b7b6ee8f9c
            migrations: true